// Copyright 2018 by BBN Technologies Corp.
// All Rights Reserved.

/**********************************************************************/
#define SERIF_VERSION_STRING "6.2"
#define SERIF_COPYRIGHT_MESSAGE "\nCopyright 2018 by Raytheon BBN Technologies Corp.\nAll Rights Reserved.\n"
#define BBN_ACCENT_COPYRIGHT_MESSAGE "\nBBN ACCENT(TM) is proprietary software owned by Raytheon BBN Technologies Corp.\n\nAll Rights Reserved.\n\nIn partnership with the U.S. Government, BBN is pleased to offer academic\nresearch institutions, or third parties conducting internally-funded\nnon-commercial research, a term-limited, non-exclusive, non-transferable\nlicense to use BBN ACCENT. Academic research institutions can use BBN ACCENT\nfor any research purpose during the term.  BBN will not claim any right to\nevent data generated by a third party's use of BBN ACCENT.\n\nPlease see BBN's End User License for complete details.\n"

/**********************************************************************/


#include "Generic/common/leak_detection.h" // This must be the first #include
#include "Generic/common/version.h"

#include "dynamic_includes/common/ProductName.h"

namespace {
	std::string& productName() {
		static std::string _productName(PRODUCT_NAME);
		return _productName;
	}
}

const char* SerifVersion::getProductName() {
	return productName().c_str();
}
const char* SerifVersion::getVersionString() {
	return SERIF_VERSION_STRING;
}
const char* SerifVersion::getCopyrightMessage() {
	if (productName() == "BBN_ACCENT") {
		return BBN_ACCENT_COPYRIGHT_MESSAGE;
	} else {
		return SERIF_COPYRIGHT_MESSAGE;
	}
}

LanguageAttribute SerifVersion::_serifLanguage = Language::UNSPECIFIED;

LanguageAttribute SerifVersion::getSerifLanguage() { 
	return _serifLanguage; 
}

void SerifVersion::setSerifLanguage(LanguageAttribute serifLanguage) { 
	_serifLanguage = serifLanguage; 
}

void SerifVersion::setProductName(const char *newName) {
	productName() = newName;
}
