// Copyright 2009 by BBN Technologies Corp.
// All Rights Reserved.

#ifndef SENTENCE_BREAKER_FACTORY_H
#define SENTENCE_BREAKER_FACTORY_H

#include "Generic/sentences/SentenceBreaker.h"
#include "Generic/sentences/StatSentenceBreaker.h"
#include "Generic/sentences/xx_SentenceBreaker.h"
#include "Generic/common/ParamReader.h"

/** Template for SentBreaker factories.  This SentenceBreaker
 * generated by this factory will depend on the parameters
 * do_sentence_breaking and use_stat_sentence_breaker. */
template<typename SentBreakerT, 
		 typename StatSentBreakerT=StatSentenceBreaker,
		 typename NullSentBreakerT=NullSentenceBreaker> 
class SentenceBreakerFactory: public SentenceBreaker::Factory {
public:
	SentenceBreaker *build() {
		if(ParamReader::hasParam("no_sentence_breaking")) {
			throw UnexpectedInputException("SentenceBreakerFactory::build()", 
			    "Parameter file includes the deprecated parameter 'no_sentence_breaking'. Use new boolean parameter 'do_sentence_breaking' instead");
		}
		else if (!ParamReader::getOptionalTrueFalseParamWithDefaultVal("do_sentence_breaking", true))
			return _new NullSentBreakerT();
		else if (ParamReader::isParamTrue("use_stat_sentence_breaker"))
			return _new StatSentBreakerT();
		else
			return _new SentBreakerT();
	}
};
	
#endif
