// Copyright 2009 by BBN Technologies Corp.
// All Rights Reserved.

#ifndef TOKENIZER_FACTORY_H
#define TOKENIZER_FACTORY_H

#include "Generic/tokens/Tokenizer.h"
#include "Generic/tokens/RegExTokenizer.h"
#include "Generic/common/ParamReader.h"

/** Template for Tokenizer factories.  This Tokenizer generated by
 * this factory will depend on the parameter use_regex_tokenizer. */
template<typename TokenizerT, 
		 typename RegexTokenizerT=RegExTokenizer>
class TokenizerFactory: public Tokenizer::Factory {
public:
	Tokenizer *build() {
		if (ParamReader::isParamTrue("use_regex_tokenizer"))
			return _new RegexTokenizerT(_new TokenizerT());
		else
			return _new TokenizerT();
	}
};
	
#endif
