#!/bin/env python

"""
Update the project files generated by cmake to have the correct
GUIDs.

By default, cmake generates new (random) GUIDs for the projects; this
script modifies those GUIDs to match the GUIDs used by other projects
to refer to these projects.
"""

GUIDS = {
    'Generic': "{B07A8563-A592-4EBC-8A6E-624531709970}",
    'Arabic':  "{05C8070A-E065-42A9-AA36-8811013EBF43}",
    'Chinese': "{C0163C5A-EBA4-4BA6-BC05-FCC8E53A5C72}",
    'English': "{BB6850AF-7FDB-4D89-B612-97BA869EA5C6}",
    }

import os, sys, re

NOOP = False # for testing

s = '	ProjectGUID="{8208B20E-EB3E-45BC-AE9D-FCA9C5622234}"'
assert re.search(r'ProjectGUID="{[A-Z0-9\-]+}"', s)


for project, guid in GUIDS.items():
    filename = os.path.join(project, project+'.vcproj')
    assert os.path.exists(filename), 'project file not found'
    contents = open(filename, 'rb').read()
    if re.search(r'ProjectGUID="%s"' % guid, contents):
        print '%s already has the right GUID' % filename
    else:
        new = re.sub(r'ProjectGUID="{[A-Z0-9\-]+}"',
                     r'ProjectGUID="%s"' % guid, contents, 1)
        assert new != contents, 'guid not found?'
        print 'Updating GUID for %s' % filename
        if NOOP:
            print '  (noop)'
        else:
            os.rename(filename, filename+'.bak')
            out = open(filename, 'wb')
            out.write(new)
            out.close()

    
